name: Markdown list linter tester

on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Markdown list linter
    steps:
      - uses: actions/checkout@v3

      - id: lint1
        name: Lint markdown lists
        uses: ClydeDz/markdown-list-linter@main
        with:
          file: markdown-lists/valid_file.md
          fail-on-error: false
      
      - run: echo ${{ steps.lint1.outputs.summary }}

      - id: lint2
        name: Lint markdown lists
        uses: ClydeDz/markdown-list-linter@main
        with:
          file: markdown-lists/unordered_lists_and_headings.md
          fail-on-error: false   
      
      - run: echo ${{ steps.lint2.outputs.summary }}

      - run: echo Step after linting
