name: Markdown to JSON tester

on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Convert files
    steps:
      - uses: actions/checkout@v3

      - name: Convert markdown to json portfolio
        uses: clydeDz/markdown-to-json@v0.1.0
        with:
          settings-json-file: markdown/portfolio.json

      - name: Convert markdown to json cta
        uses: clydeDz/markdown-to-json@v0.1.0
      
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          path: ./public/markdown-to-json 
